/* items.js - vanilla Minecraft items with real texture paths
 * Textures: https://github.com/PrismarineJS/minecraft-assets (data/1.21.4/items, data/1.21.4/blocks)
 * Key is the canonical material name we write to global-shops.yml.
 */
const CREATIVE_CATS = [
    "Building Blocks",
    "Decoration",
    "Redstone",
    "Transportation",
    "Combat",
    "Tools",
    "Food & Farming",
    "Materials",
    "Brewing"
];

// [key, title, [cat], textureOverride?]
const ITEMS = [
    // ---- Building Blocks ----
    ["STONE", "Stone", 0],
    ["COBBLESTONE", "Cobblestone", 0],
    ["DIRT", "Dirt", 0],
    ["GRASS_BLOCK", "Grass Block", 0, "grass_block_top"],
    ["SAND", "Sand", 0],
    ["RED_SAND", "Red Sand", 0],
    ["GRAVEL", "Gravel", 0],
    ["GRANITE", "Granite", 0],
    ["POLISHED_GRANITE", "Polished Granite", 0],
    ["DIORITE", "Diorite", 0],
    ["POLISHED_DIORITE", "Polished Diorite", 0],
    ["ANDESITE", "Andesite", 0],
    ["POLISHED_ANDESITE", "Polished Andesite", 0],
    ["BEDROCK", "Bedrock", 0],
    ["OAK_LOG", "Oak Log", 0],
    ["SPRUCE_LOG", "Spruce Log", 0],
    ["BIRCH_LOG", "Birch Log", 0],
    ["JUNGLE_LOG", "Jungle Log", 0],
    ["ACACIA_LOG", "Acacia Log", 0],
    ["DARK_OAK_LOG", "Dark Oak Log", 0],
    ["CHERRY_LOG", "Cherry Log", 0],
    ["OAK_PLANKS", "Oak Planks", 0],
    ["SPRUCE_PLANKS", "Spruce Planks", 0],
    ["BIRCH_PLANKS", "Birch Planks", 0],
    ["JUNGLE_PLANKS", "Jungle Planks", 0],
    ["ACACIA_PLANKS", "Acacia Planks", 0],
    ["DARK_OAK_PLANKS", "Dark Oak Planks", 0],
    ["CHERRY_PLANKS", "Cherry Planks", 0],
    ["CRIMSON_PLANKS", "Crimson Planks", 0],
    ["WARPED_PLANKS", "Warped Planks", 0],
    ["OAK_STAIRS", "Oak Stairs", 0],
    ["SPRUCE_STAIRS", "Spruce Stairs", 0],
    ["BIRCH_STAIRS", "Birch Stairs", 0],
    ["JUNGLE_STAIRS", "Jungle Stairs", 0],
    ["ACACIA_STAIRS", "Acacia Stairs", 0],
    ["DARK_OAK_STAIRS", "Dark Oak Stairs", 0],
    ["COBBLESTONE_STAIRS", "Cobblestone Stairs", 0],
    ["STONE_STAIRS", "Stone Stairs", 0],
    ["SANDSTONE", "Sandstone", 0],
    ["RED_SANDSTONE", "Red Sandstone", 0],
    ["SANDSTONE_STAIRS", "Sandstone Stairs", 0],
    ["BRICKS", "Bricks", 0],
    ["BRICK_STAIRS", "Brick Stairs", 0],
    ["STONE_BRICKS", "Stone Bricks", 0],
    ["CRACKED_STONE_BRICKS", "Cracked Stone Bricks", 0],
    ["MOSSY_STONE_BRICKS", "Mossy Stone Bricks", 0],
    ["CHISELED_STONE_BRICKS", "Chiseled Stone Bricks", 0],
    ["STONE_BRICK_STAIRS", "Stone Brick Stairs", 0],
    ["NETHER_BRICKS", "Nether Bricks", 0],
    ["RED_NETHER_BRICKS", "Red Nether Bricks", 0],
    ["NETHER_BRICK_STAIRS", "Nether Brick Stairs", 0],
    ["NETHERRACK", "Netherrack", 0],
    ["QUARTZ_BLOCK", "Quartz Block", 0],
    ["QUARTZ_STAIRS", "Quartz Stairs", 0],
    ["CHISELED_QUARTZ_BLOCK", "Chiseled Quartz", 0],
    ["PURPUR_BLOCK", "Purpur Block", 0],
    ["PURPUR_STAIRS", "Purpur Stairs", 0],
    ["PRISMARINE", "Prismarine", 0],
    ["PRISMARINE_BRICKS", "Prismarine Bricks", 0],
    ["DARK_PRISMARINE", "Dark Prismarine", 0],
    ["SEA_LANTERN", "Sea Lantern", 0],
    ["OBSIDIAN", "Obsidian", 0],
    ["CRYING_OBSIDIAN", "Crying Obsidian", 0],
    ["END_STONE", "End Stone", 0],
    ["END_STONE_BRICKS", "End Stone Bricks", 0],
    ["PACKED_ICE", "Packed Ice", 0],
    ["BLUE_ICE", "Blue Ice", 0],
    ["ICE", "Ice", 0],
    ["SNOW_BLOCK", "Snow Block", 0],
    ["CLAY", "Clay", 0],
    ["SOUL_SAND", "Soul Sand", 0],
    ["SOUL_SOIL", "Soul Soil", 0],
    ["COAL_ORE", "Coal Ore", 0],
    ["DEEPSLATE_COAL_ORE", "Deepslate Coal Ore", 0],
    ["COPPER_ORE", "Copper Ore", 0],
    ["DEEPSLATE_COPPER_ORE", "Deepslate Copper Ore", 0],
    ["IRON_ORE", "Iron Ore", 0],
    ["DEEPSLATE_IRON_ORE", "Deepslate Iron Ore", 0],
    ["GOLD_ORE", "Gold Ore", 0],
    ["DEEPSLATE_GOLD_ORE", "Deepslate Gold Ore", 0],
    ["REDSTONE_ORE", "Redstone Ore", 0],
    ["DEEPSLATE_REDSTONE_ORE", "Deepslate Redstone Ore", 0],
    ["LAPIS_ORE", "Lapis Ore", 0],
    ["DEEPSLATE_LAPIS_ORE", "Deepslate Lapis Ore", 0],
    ["DIAMOND_ORE", "Diamond Ore", 0],
    ["DEEPSLATE_DIAMOND_ORE", "Deepslate Diamond Ore", 0],
    ["EMERALD_ORE", "Emerald Ore", 0],
    ["NETHER_GOLD_ORE", "Nether Gold Ore", 0],
    ["ANCIENT_DEBRIS", "Ancient Debris", 0],
    ["COAL_BLOCK", "Coal Block", 0],
    ["IRON_BLOCK", "Iron Block", 0],
    ["COPPER_BLOCK", "Copper Block", 0],
    ["GOLD_BLOCK", "Gold Block", 0],
    ["DIAMOND_BLOCK", "Diamond Block", 0],
    ["EMERALD_BLOCK", "Emerald Block", 0],
    ["REDSTONE_BLOCK", "Redstone Block", 0],
    ["LAPIS_BLOCK", "Lapis Block", 0],
    ["NETHERITE_BLOCK", "Netherite Block", 0],
    ["AMETHYST_BLOCK", "Amethyst Block", 0],
    ["GLOWSTONE", "Glowstone", 0],
    ["MAGMA_BLOCK", "Magma Block", 0],
    ["SHROOMLIGHT", "Shroomlight", 0],
    ["MYCELIUM", "Mycelium", 0],
    ["SLIME_BLOCK", "Slime Block", 0],
    ["HONEY_BLOCK", "Honey Block", 0],
    ["CRAFTING_TABLE", "Crafting Table", 0],
    ["FURNACE", "Furnace", 0],
    ["BLAST_FURNACE", "Blast Furnace", 0],
    ["SMOKER", "Smoker", 0],
    ["ANVIL", "Anvil", 0],
    ["ENCHANTING_TABLE", "Enchanting Table", 0],
    ["BEACON", "Beacon", 0],
    // ---- Decoration ----
    ["OAK_DOOR", "Oak Door", 1],
    ["IRON_DOOR", "Iron Door", 1],
    ["SPRUCE_DOOR", "Spruce Door", 1],
    ["BIRCH_DOOR", "Birch Door", 1],
    ["JUNGLE_DOOR", "Jungle Door", 1],
    ["ACACIA_DOOR", "Acacia Door", 1],
    ["DARK_OAK_DOOR", "Dark Oak Door", 1],
    ["OAK_TRAPDOOR", "Oak Trapdoor", 1],
    ["IRON_TRAPDOOR", "Iron Trapdoor", 1],
    ["OAK_FENCE", "Oak Fence", 1],
    ["SPRUCE_FENCE", "Spruce Fence", 1],
    ["NETHER_BRICK_FENCE", "Nether Brick Fence", 1],
    ["OAK_FENCE_GATE", "Oak Fence Gate", 1],
    ["OAK_SLAB", "Oak Slab", 1],
    ["STONE_SLAB", "Stone Slab", 1],
    ["SANDSTONE_SLAB", "Sandstone Slab", 1],
    ["QUARTZ_SLAB", "Quartz Slab", 1],
    ["COBBLESTONE_SLAB", "Cobblestone Slab", 1],
    ["BRICK_SLAB", "Brick Slab", 1],
    ["LADDER", "Ladder", 1],
    ["IRON_BARS", "Iron Bars", 1],
    ["GLASS", "Glass", 1],
    ["GLASS_PANE", "Glass Pane", 1],
    ["WHITE_STAINED_GLASS", "White Stained Glass", 1],
    ["ORANGE_STAINED_GLASS", "Orange Stained Glass", 1],
    ["MAGENTA_STAINED_GLASS", "Magenta Stained Glass", 1],
    ["LIGHT_BLUE_STAINED_GLASS", "Light Blue Stained Glass", 1],
    ["YELLOW_STAINED_GLASS", "Yellow Stained Glass", 1],
    ["LIME_STAINED_GLASS", "Lime Stained Glass", 1],
    ["PINK_STAINED_GLASS", "Pink Stained Glass", 1],
    ["GRAY_STAINED_GLASS", "Gray Stained Glass", 1],
    ["LIGHT_GRAY_STAINED_GLASS", "Light Gray Stained Glass", 1],
    ["CYAN_STAINED_GLASS", "Cyan Stained Glass", 1],
    ["PURPLE_STAINED_GLASS", "Purple Stained Glass", 1],
    ["BLUE_STAINED_GLASS", "Blue Stained Glass", 1],
    ["BROWN_STAINED_GLASS", "Brown Stained Glass", 1],
    ["GREEN_STAINED_GLASS", "Green Stained Glass", 1],
    ["RED_STAINED_GLASS", "Red Stained Glass", 1],
    ["BLACK_STAINED_GLASS", "Black Stained Glass", 1],
    ["WHITE_WOOL", "White Wool", 1],
    ["ORANGE_WOOL", "Orange Wool", 1],
    ["MAGENTA_WOOL", "Magenta Wool", 1],
    ["LIGHT_BLUE_WOOL", "Light Blue Wool", 1],
    ["YELLOW_WOOL", "Yellow Wool", 1],
    ["LIME_WOOL", "Lime Wool", 1],
    ["PINK_WOOL", "Pink Wool", 1],
    ["GRAY_WOOL", "Gray Wool", 1],
    ["LIGHT_GRAY_WOOL", "Light Gray Wool", 1],
    ["CYAN_WOOL", "Cyan Wool", 1],
    ["PURPLE_WOOL", "Purple Wool", 1],
    ["BLUE_WOOL", "Blue Wool", 1],
    ["BROWN_WOOL", "Brown Wool", 1],
    ["GREEN_WOOL", "Green Wool", 1],
    ["RED_WOOL", "Red Wool", 1],
    ["BLACK_WOOL", "Black Wool", 1],
    ["WHITE_CARPET", "White Carpet", 1],
    ["BLACK_CARPET", "Black Carpet", 1],
    ["RED_CARPET", "Red Carpet", 1],
    ["BLUE_CARPET", "Blue Carpet", 1],
    ["WHITE_TERRACOTTA", "White Terracotta", 1],
    ["ORANGE_TERRACOTTA", "Orange Terracotta", 1],
    ["TERRACOTTA", "Terracotta", 1],
    ["MAGENTA_TERRACOTTA", "Magenta Terracotta", 1],
    ["LIGHT_BLUE_TERRACOTTA", "Light Blue Terracotta", 1],
    ["YELLOW_TERRACOTTA", "Yellow Terracotta", 1],
    ["LIME_TERRACOTTA", "Lime Terracotta", 1],
    ["PINK_TERRACOTTA", "Pink Terracotta", 1],
    ["GRAY_TERRACOTTA", "Gray Terracotta", 1],
    ["LIGHT_GRAY_TERRACOTTA", "Light Gray Terracotta", 1],
    ["CYAN_TERRACOTTA", "Cyan Terracotta", 1],
    ["PURPLE_TERRACOTTA", "Purple Terracotta", 1],
    ["BLUE_TERRACOTTA", "Blue Terracotta", 1],
    ["BROWN_TERRACOTTA", "Brown Terracotta", 1],
    ["GREEN_TERRACOTTA", "Green Terracotta", 1],
    ["RED_TERRACOTTA", "Red Terracotta", 1],
    ["BLACK_TERRACOTTA", "Black Terracotta", 1],
    ["CHEST", "Chest", 1],
    ["TRAPPED_CHEST", "Trapped Chest", 1],
    ["ENDER_CHEST", "Ender Chest", 1],
    ["BARREL", "Barrel", 1],
    ["LECTERN", "Lectern", 1],
    ["BOOKSHELF", "Bookshelf", 1],
    ["ITEM_FRAME", "Item Frame", 1],
    ["PAINTING", "Painting", 1],
    ["FLOWER_POT", "Flower Pot", 1],
    ["OAK_SIGN", "Oak Sign", 1],
    ["OAK_SAPLING", "Oak Sapling", 1],
    ["SPRUCE_SAPLING", "Spruce Sapling", 1],
    ["BIRCH_SAPLING", "Birch Sapling", 1],
    ["JUNGLE_SAPLING", "Jungle Sapling", 1],
    ["ACACIA_SAPLING", "Acacia Sapling", 1],
    ["DARK_OAK_SAPLING", "Dark Oak Sapling", 1],
    ["SHORT_GRASS", "Short Grass", 1, "short_grass"],
    ["FERN", "Fern", 1],
    ["DEAD_BUSH", "Dead Bush", 1],
    ["DANDELION", "Dandelion", 1],
    ["POPPY", "Poppy", 1],
    ["BLUE_ORCHID", "Blue Orchid", 1],
    ["ALLIUM", "Allium", 1],
    ["AZURE_BLUET", "Azure Bluet", 1],
    ["RED_TULIP", "Red Tulip", 1],
    ["ORANGE_TULIP", "Orange Tulip", 1],
    ["WHITE_TULIP", "White Tulip", 1],
    ["PINK_TULIP", "Pink Tulip", 1],
    ["OXEYE_DAISY", "Oxeye Daisy", 1],
    ["CORNFLOWER", "Cornflower", 1],
    ["LILY_OF_THE_VALLEY", "Lily of the Valley", 1],
    ["WITHER_ROSE", "Wither Rose", 1],
    ["SUGAR_CANE", "Sugar Cane", 1],
    ["CACTUS", "Cactus", 1],
    ["VINE", "Vine", 1],
    ["LILY_PAD", "Lily Pad", 1],
    ["SEAGRASS", "Seagrass", 1],
    ["KELP", "Kelp", 1],
    ["BAMBOO", "Bamboo", 1],
    ["SUNFLOWER", "Sunflower", 1],
    ["LILAC", "Lilac", 1],
    ["ROSE_BUSH", "Rose Bush", 1],
    ["PEONY", "Peony", 1],
    ["BROWN_MUSHROOM", "Brown Mushroom", 1],
    ["RED_MUSHROOM", "Red Mushroom", 1],
    ["TORCH", "Torch", 1],
    ["SOUL_TORCH", "Soul Torch", 1],
    ["LANTERN", "Lantern", 1],
    ["SOUL_LANTERN", "Soul Lantern", 1],
    ["JACK_O_LANTERN", "Jack o'Lantern", 1],
    ["CAMPFIRE", "Campfire", 1],
    ["SOUL_CAMPFIRE", "Soul Campfire", 1],
    ["BELL", "Bell", 1],
    ["AMETHYST_SHARD", "Amethyst Shard", 1],
    ["POINTED_DRIPSTONE", "Pointed Dripstone", 1],
    ["CALCITE", "Calcite", 1],
    ["TUFF", "Tuff", 1],
    ["DRIPSTONE_BLOCK", "Dripstone Block", 1],
    ["SPONGE", "Sponge", 1],
    // ---- Redstone ----
    ["REDSTONE", "Redstone Dust", 2],
    ["REDSTONE_TORCH", "Redstone Torch", 2],
    ["LEVER", "Lever", 2],
    ["STONE_BUTTON", "Stone Button", 2],
    ["OAK_BUTTON", "Oak Button", 2],
    ["STONE_PRESSURE_PLATE", "Stone Pressure Plate", 2],
    ["OAK_PRESSURE_PLATE", "Oak Pressure Plate", 2],
    ["HEAVY_WEIGHTED_PRESSURE_PLATE", "Heavy Pressure Plate", 2],
    ["LIGHT_WEIGHTED_PRESSURE_PLATE", "Light Pressure Plate", 2],
    ["REPEATER", "Redstone Repeater", 2],
    ["COMPARATOR", "Redstone Comparator", 2],
    ["PISTON", "Piston", 2],
    ["STICKY_PISTON", "Sticky Piston", 2],
    ["OBSERVER", "Observer", 2],
    ["DISPENSER", "Dispenser", 2],
    ["DROPPER", "Dropper", 2],
    ["HOPPER", "Hopper", 2],
    ["REDSTONE_LAMP", "Redstone Lamp", 2],
    ["TARGET", "Target Block", 2],
    ["DAYLIGHT_DETECTOR", "Daylight Detector", 2],
    ["TRIPWIRE_HOOK", "Tripwire Hook", 2],
    ["NOTE_BLOCK", "Note Block", 2],
    ["JUKEBOX", "Jukebox", 2],
    ["TNT", "TNT", 2],
    // ---- Transportation ----
    ["MINECART", "Minecart", 3],
    ["CHEST_MINECART", "Minecart with Chest", 3],
    ["FURNACE_MINECART", "Minecart with Furnace", 3],
    ["TNT_MINECART", "Minecart with TNT", 3],
    ["HOPPER_MINECART", "Minecart with Hopper", 3],
    ["RAIL", "Rail", 3],
    ["POWERED_RAIL", "Powered Rail", 3],
    ["DETECTOR_RAIL", "Detector Rail", 3],
    ["ACTIVATOR_RAIL", "Activator Rail", 3],
    ["OAK_BOAT", "Oak Boat", 3],
    ["SPRUCE_BOAT", "Spruce Boat", 3],
    ["BIRCH_BOAT", "Birch Boat", 3],
    ["JUNGLE_BOAT", "Jungle Boat", 3],
    ["ACACIA_BOAT", "Acacia Boat", 3],
    ["DARK_OAK_BOAT", "Dark Oak Boat", 3],
    ["ELYTRA", "Elytra", 3],
    ["SADDLE", "Saddle", 3],
    ["CARROT_ON_A_STICK", "Carrot on a Stick", 3],
    ["WARPED_FUNGUS_ON_A_STICK", "Warped Fungus on a Stick", 3],
    ["ENDER_PEARL", "Ender Pearl", 3],
    ["ENDER_EYE", "Ender Eye", 3],
    ["CHORUS_FRUIT", "Chorus Fruit", 3],
    ["DRAGON_BREATH", "Dragon's Breath", 3],
    // ---- Combat ----
    ["WOODEN_SWORD", "Wooden Sword", 4],
    ["STONE_SWORD", "Stone Sword", 4],
    ["IRON_SWORD", "Iron Sword", 4],
    ["GOLDEN_SWORD", "Golden Sword", 4],
    ["DIAMOND_SWORD", "Diamond Sword", 4],
    ["NETHERITE_SWORD", "Netherite Sword", 4],
    ["SHIELD", "Shield", 4],
    ["BOW", "Bow", 4],
    ["CROSSBOW", "Crossbow", 4],
    ["ARROW", "Arrow", 4],
    ["TIPPED_ARROW", "Tipped Arrow", 4],
    ["SPECTRAL_ARROW", "Spectral Arrow", 4],
    ["TRIDENT", "Trident", 4],
    ["IRON_AXE", "Iron Axe", 4],
    ["DIAMOND_AXE", "Diamond Axe", 4],
    ["NETHERITE_AXE", "Netherite Axe", 4],
    ["LEATHER_HELMET", "Leather Helmet", 4],
    ["LEATHER_CHESTPLATE", "Leather Chestplate", 4],
    ["LEATHER_LEGGINGS", "Leather Leggings", 4],
    ["LEATHER_BOOTS", "Leather Boots", 4],
    ["CHAINMAIL_HELMET", "Chainmail Helmet", 4],
    ["CHAINMAIL_CHESTPLATE", "Chainmail Chestplate", 4],
    ["CHAINMAIL_LEGGINGS", "Chainmail Leggings", 4],
    ["CHAINMAIL_BOOTS", "Chainmail Boots", 4],
    ["IRON_HELMET", "Iron Helmet", 4],
    ["IRON_CHESTPLATE", "Iron Chestplate", 4],
    ["IRON_LEGGINGS", "Iron Leggings", 4],
    ["IRON_BOOTS", "Iron Boots", 4],
    ["GOLDEN_HELMET", "Golden Helmet", 4],
    ["GOLDEN_CHESTPLATE", "Golden Chestplate", 4],
    ["GOLDEN_LEGGINGS", "Golden Leggings", 4],
    ["GOLDEN_BOOTS", "Golden Boots", 4],
    ["DIAMOND_HELMET", "Diamond Helmet", 4],
    ["DIAMOND_CHESTPLATE", "Diamond Chestplate", 4],
    ["DIAMOND_LEGGINGS", "Diamond Leggings", 4],
    ["DIAMOND_BOOTS", "Diamond Boots", 4],
    ["NETHERITE_HELMET", "Netherite Helmet", 4],
    ["NETHERITE_CHESTPLATE", "Netherite Chestplate", 4],
    ["NETHERITE_LEGGINGS", "Netherite Leggings", 4],
    ["NETHERITE_BOOTS", "Netherite Boots", 4],
    ["TOTEM_OF_UNDYING", "Totem of Undying", 4],
    ["SNOWBALL", "Snowball", 4],
    ["EGG", "Egg", 4],
    ["FIRE_CHARGE", "Fire Charge", 4],
    // ---- Tools & Utilities ----
    ["WOODEN_PICKAXE", "Wooden Pickaxe", 5],
    ["STONE_PICKAXE", "Stone Pickaxe", 5],
    ["IRON_PICKAXE", "Iron Pickaxe", 5],
    ["GOLDEN_PICKAXE", "Golden Pickaxe", 5],
    ["DIAMOND_PICKAXE", "Diamond Pickaxe", 5],
    ["NETHERITE_PICKAXE", "Netherite Pickaxe", 5],
    ["WOODEN_SHOVEL", "Wooden Shovel", 5],
    ["STONE_SHOVEL", "Stone Shovel", 5],
    ["IRON_SHOVEL", "Iron Shovel", 5],
    ["DIAMOND_SHOVEL", "Diamond Shovel", 5],
    ["WOODEN_HOE", "Wooden Hoe", 5],
    ["STONE_HOE", "Stone Hoe", 5],
    ["IRON_HOE", "Iron Hoe", 5],
    ["DIAMOND_HOE", "Diamond Hoe", 5],
    ["WOODEN_AXE", "Wooden Axe", 5],
    ["STONE_AXE", "Stone Axe", 5],
    ["GOLDEN_AXE", "Golden Axe", 5],
    ["DIAMOND_AXE_TOOL", "", 5, "diamond_axe"],
    ["FLINT_AND_STEEL", "Flint and Steel", 5],
    ["SHEARS", "Shears", 5],
    ["COMPASS", "Compass", 5],
    ["RECOVERY_COMPASS", "Recovery Compass", 5],
    ["CLOCK", "Clock", 5],
    ["NAME_TAG", "Name Tag", 5],
    ["LEAD", "Lead", 5],
    ["FISHING_ROD", "Fishing Rod", 5],
    ["BRUSH", "Brush", 5],
    ["SPYGLASS", "Spyglass", 5],
    ["BUCKET", "Bucket", 5],
    ["WATER_BUCKET", "Water Bucket", 5],
    ["LAVA_BUCKET", "Lava Bucket", 5],
    ["MILK_BUCKET", "Milk Bucket", 5],
    ["COD_BUCKET", "Bucket of Cod", 5],
    ["MAP", "Map", 5],
    ["WRITABLE_BOOK", "Book and Quill", 5],
    ["WRITTEN_BOOK", "Written Book", 5],
    ["BOOK", "Book", 5],
    ["ENCHANTED_BOOK", "Enchanted Book", 5],
    ["PAPER", "Paper", 5],
    ["MUSIC_DISC_13", "Music Disc (13)", 5],
    ["MUSIC_DISC_CAT", "Music Disc (Cat)", 5],
    ["GOAT_HORN", "Goat Horn", 5],
    ["EXPERIENCE_BOTTLE", "Bottle o' Enchanting", 5],
    // ---- Food & Farming ----
    ["APPLE", "Apple", 6],
    ["GOLDEN_APPLE", "Golden Apple", 6],
    ["ENCHANTED_GOLDEN_APPLE", "Enchanted Golden Apple", 6, "golden_apple"],
    ["GOLDEN_CARROT", "Golden Carrot", 6],
    ["CARROT", "Carrot", 6],
    ["POTATO", "Potato", 6],
    ["BAKED_POTATO", "Baked Potato", 6],
    ["POISONOUS_POTATO", "Poisonous Potato", 6],
    ["WHEAT", "Wheat", 6],
    ["WHEAT_SEEDS", "Wheat Seeds", 6],
    ["BEETROOT", "Beetroot", 6],
    ["BEETROOT_SEEDS", "Beetroot Seeds", 6],
    ["MELON_SLICE", "Melon Slice", 6],
    ["PUMPKIN", "Pumpkin", 6],
    ["PUMPKIN_SEEDS", "Pumpkin Seeds", 6],
    ["MELON_SEEDS", "Melon Seeds", 6],
    ["SWEET_BERRIES", "Sweet Berries", 6],
    ["GLOW_BERRIES", "Glow Berries", 6],
    ["BREAD", "Bread", 6],
    ["COOKIE", "Cookie", 6],
    ["CAKE", "Cake", 6],
    ["PUMPKIN_PIE", "Pumpkin Pie", 6],
    ["SUGAR", "Sugar", 6],
    ["RAW_BEEF", "Raw Beef", 6],
    ["STEAK", "Steak", 6],
    ["COOKED_CHICKEN", "Cooked Chicken", 6],
    ["CHICKEN", "Raw Chicken", 6],
    ["PORKCHOP", "Raw Porkchop", 6],
    ["COOKED_PORKCHOP", "Cooked Porkchop", 6],
    ["MUTTON", "Raw Mutton", 6],
    ["COOKED_MUTTON", "Cooked Mutton", 6],
    ["RABBIT", "Raw Rabbit", 6],
    ["COOKED_RABBIT", "Cooked Rabbit", 6],
    ["RABBIT_STEW", "Rabbit Stew", 6],
    ["COOKED_COD", "Cooked Cod", 6],
    ["COD", "Raw Cod", 6],
    ["SALMON", "Raw Salmon", 6],
    ["COOKED_SALMON", "Cooked Salmon", 6],
    ["TROPICAL_FISH", "Tropical Fish", 6],
    ["PUFFERFISH", "Pufferfish", 6],
    ["MUSHROOM_STEW", "Mushroom Stew", 6],
    ["BEETROOT_SOUP", "Beetroot Soup", 6],
    ["SUSPICIOUS_STEW", "Suspicious Stew", 6],
    ["DRIED_KELP", "Dried Kelp", 6],
    ["HONEY_BOTTLE", "Honey Bottle", 6],
    ["COCOA_BEANS", "Cocoa Beans", 6],
    ["DYE_WHITE", "", 6, "white_dye"],
    ["DYE_BLACK", "", 6, "black_dye"],
    ["DYE_RED", "", 6, "red_dye"],
    ["DYE_GREEN", "", 6, "green_dye"],
    ["DYE_BLUE", "", 6, "blue_dye"],
    ["DYE_BROWN", "", 6, "brown_dye"],
    ["DYE_YELLOW", "", 6, "yellow_dye"],
    ["DYE_PURPLE", "", 6, "purple_dye"],
    ["DYE_PINK", "", 6, "pink_dye"],
    ["DYE_CYAN", "", 6, "cyan_dye"],
    ["DYE_ORANGE", "", 6, "orange_dye"],
    ["DYE_LIME", "", 6, "lime_dye"],
    ["DYE_LIGHT_GRAY", "", 6, "light_gray_dye"],
    ["DYE_GRAY", "", 6, "gray_dye"],
    ["DYE_LIGHT_BLUE", "", 6, "light_blue_dye"],
    ["DYE_MAGENTA", "", 6, "magenta_dye"],
    ["DYE_INK_SAC", "", 6, "ink_sac"],
    ["BONE_MEAL", "Bone Meal", 6],
    ["LEATHER", "Leather", 6],
    ["RABBIT_HIDE", "Rabbit Hide", 6],
    ["SPIDER_EYE", "Spider Eye", 6],
    ["FERMENTED_SPIDER_EYE", "Fermented Spider Eye", 6],
    ["ROTTEN_FLESH", "Rotten Flesh", 6],
    ["BONE", "Bone", 6],
    ["STRING", "String", 6],
    ["FEATHER", "Feather", 6],
    ["GUNPOWDER", "Gunpowder", 6],
    ["FLINT", "Flint", 6],
    ["BLAZE_ROD", "Blaze Rod", 6],
    ["BLAZE_POWDER", "Blaze Powder", 6],
    ["ENDER_PEARL_FARM", "", 6, "ender_pearl"],
    // ---- Materials ----
    ["IRON_INGOT", "Iron Ingot", 7],
    ["GOLD_INGOT", "Gold Ingot", 7],
    ["COPPER_INGOT", "Copper Ingot", 7],
    ["NETHERITE_INGOT", "Netherite Ingot", 7],
    ["NETHERITE_SCRAP", "Netherite Scrap", 7],
    ["DIAMOND", "Diamond", 7],
    ["EMERALD", "Emerald", 7],
    ["LAPIS_LAZULI", "Lapis Lazuli", 7],
    ["QUARTZ", "Nether Quartz", 7],
    ["AMETHYST_SHARD_MAT", "", 7, "amethyst_shard"],
    ["COAL", "Coal", 7],
    ["CHARCOAL", "Charcoal", 7],
    ["RAW_IRON", "Raw Iron", 7],
    ["RAW_GOLD", "Raw Gold", 7],
    ["RAW_COPPER", "Raw Copper", 7],
    ["STICK", "Stick", 7],
    ["PRISMARINE_CRYSTALS", "Prismarine Crystals", 7],
    ["PRISMARINE_SHARD", "Prismarine Shard", 7],
    ["SLIME_BALL", "Slimeball", 7],
    ["EGG_MAT", "", 7, "egg"],
    ["ENDER_PEARL_MAT", "", 7, "ender_pearl"],
    ["ENDER_EYE_MAT", "", 7, "ender_eye"],
    ["NAUTILUS_SHELL", "Nautilus Shell", 7],
    ["HEART_OF_THE_SEA", "Heart of the Sea", 7],
    ["PHANTOM_MEMBRANE", "Phantom Membrane", 7],
    ["SHULKER_SHELL", "Shulker Shell", 7],
    ["POPPED_CHORUS_FRUIT", "Popped Chorus Fruit", 7],
    ["GHAST_TEAR", "Ghast Tear", 7],
    ["DIAMOND_FILE", "", 7, "diamond"],
    // ---- Brewing ----
    ["GLASS_BOTTLE", "Glass Bottle", 8],
    ["POTION", "Potion", 8],
    ["SPLASH_POTION", "Splash Potion", 8],
    ["LINGERING_POTION", "Lingering Potion", 8],
    ["BREWING_STAND", "Brewing Stand", 8],
    ["CAULDRON", "Cauldron", 8],
    ["GLISTERING_MELON_SLICE", "Glistering Melon Slice", 8],
    ["GOLDEN_CARROT_BREW", "", 8, "golden_carrot"],
    ["SUGAR_BREW", "", 8, "sugar"],
    ["RABBIT_FOOT", "Rabbit's Foot", 8],
    ["BLAZE_POWDER_BREW", "", 8, "blaze_powder"],
    ["GHAST_TEAR_BREW", "", 8, "ghast_tear"],
    ["SPIDER_EYE_BREW", "", 8, "spider_eye"],
    ["FERMENTED_SPIDER_EYE_BREW", "", 8, "fermented_spider_eye"],
    ["MAGMA_CREAM", "Magma Cream", 8],
    ["GLOWSTONE_DUST", "Glowstone Dust", 8],
    ["REDSTONE_BREW", "", 8, "redstone"],
];

// Build lookup
const ITEM_BY_KEY = {};
ITEMS.forEach((it, i) => { ITEM_BY_KEY[it[0]] = i; });

function texName(it) {
    return (it.length > 3 && it[3]) ? it[3] : it[0].toLowerCase();
}
const TEX_BASE = "https://raw.githubusercontent.com/PrismarineJS/minecraft-assets/master/data/1.21.4/";
// Remap for items whose flat icon doesn't exist in minecraft-assets
// (stairs/slabs/fences/chests render from 3D models, so we reuse a face texture).
const TEX_REMAP = {
    quartz_block: "quartz_block_top",
    snow_block: "snow",
    ancient_debris: "ancient_debris_top",
    magma_block: "magma",
    mycelium: "mycelium_top",
    honey_block: "honey_block_top",
    crafting_table: "crafting_table_top",
    furnace: "furnace_front",
    blast_furnace: "blast_furnace_front",
    smoker: "smoker_front",
    enchanting_table: "enchanting_table_top",
    glass_pane: "glass_pane_top",
    white_carpet: "white_wool",
    black_carpet: "black_wool",
    red_carpet: "red_wool",
    blue_carpet: "blue_wool",
    oak_fence: "oak_planks",
    spruce_fence: "spruce_planks",
    nether_brick_fence: "nether_bricks",
    oak_fence_gate: "oak_planks",
    oak_slab: "oak_planks",
    stone_slab: "stone",
    sandstone_slab: "sandstone",
    quartz_slab: "quartz_block_top",
    cobblestone_slab: "cobblestone",
    brick_slab: "bricks",
    oak_stairs: "oak_planks",
    spruce_stairs: "spruce_planks",
    birch_stairs: "birch_planks",
    jungle_stairs: "jungle_planks",
    acacia_stairs: "acacia_planks",
    dark_oak_stairs: "dark_oak_planks",
    cobblestone_stairs: "cobblestone",
    stone_stairs: "stone",
    sandstone_stairs: "sandstone",
    brick_stairs: "bricks",
    stone_brick_stairs: "stone_bricks",
    nether_brick_stairs: "nether_bricks",
    quartz_stairs: "quartz_block_top",
    purpur_stairs: "purpur_block",
    chest: "/chest_item",
    trapped_chest: "/trapped_chest",
    ender_chest: "/ender_chest",
    shield: "entity/shield_base",
    barrel: "barrel_top",
    lectern: "lectern_top",
    cactus: "cactus_side",
    sunflower: "sunflower_front",
    lilac: "lilac_top",
    rose_bush: "rose_bush_top",
    peony: "peony_top",
    stone_button: "stone",
    oak_button: "oak_planks",
    stone_pressure_plate: "stone",
    oak_pressure_plate: "oak_planks",
    heavy_weighted_pressure_plate: "iron_block",
    light_weighted_pressure_plate: "gold_block",
    piston: "piston_top",
    sticky_piston: "piston_top_sticky",
    observer: "observer_front",
    dispenser: "dispenser_front",
    dropper: "dropper_front",
    target: "target_top",
    daylight_detector: "daylight_detector_top",
    jukebox: "jukebox_top",
    tnt: "tnt_side",
    crossbow: "crossbow_standby",
    tipped_arrow: "tipped_arrow_base",
    compass: "compass_00",
    recovery_compass: "recovery_compass_00",
    clock: "clock_00",
    pumpkin: "pumpkin_side",
    raw_beef: "beef",
    steak: "cooked_beef"
};
function texFile(it) {
    const t = texName(it);
    const remap = TEX_REMAP[t];
    return remap || t;
}
function texPath(it) {
    const t = texFile(it);
    if (t.indexOf("/") === 0) return t.slice(1) + ".png";
    return TEX_BASE + (t.indexOf("/") !== -1 ? "" : "items/") + t + ".png";
}
function blockTexPath(it) {
    const t = texFile(it);
    if (t.indexOf("/") !== -1) return null;
    return TEX_BASE + "blocks/" + t + ".png";
}